server:
  applicationConnectors:
    - type: http
      port: 8888
  adminConnectors:
    - type: http
      port: 8889
  rootPath: /api
  applicationContextPath: /

logging:
  level: INFO
  loggers:
    com.campspot: DEBUG

redis:
  host: 192.168.0.2 
  port: 6379